server.port=8003
spring.application.name=microservicio-coche

#CONFIGURACION DE DATASOURCE A NIVEL LOCAL
spring.datasource.url=jdbc:mysql://localhost:3306/microservice_coche
spring.datasource.username=root
spring.datasource.password=#Cu213lona1993
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.main.allow-circular-references=true
spring.main.allow-bean-definition-overriding=true

#CONFIGURACION DE DATASOURCE IMPLEMENTANDO DOCKER
#spring.datasource.url=jdbc:mysql://localhost:3307/microservice-coche?serverTimeZone=UTC&allowPublicKeyRetrieval=true&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=secret
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.open-in-view=false

# Elasticsearch
elasticsearch.host=http://localhost:9200
elasticsearch.api-key=bHVSSm9aOEJWenk0ckRCdU9CdlI6clkxTmpZVUhOeXg4WEY5OUVTc0dHQQ==
